version: '3'

tasks:
  setup:
    desc: Setup the project for development
    cmds:
      - bun install
  build:
    desc: Build the project
    cmds:
      - bunx --bun astro build
  dev:
    desc: Run the development server
    cmds:
      - bunx --bun astro dev
